name: dcs
description: "Dental clinic management system for Arab American University Jenin"
publish_to: 'AAUP'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  intl: ^0.20.2
  provider: ^6.1.4
  connectivity_plus: ^7.0.0
  font_awesome_flutter: ^10.8.0  
  url_launcher: ^6.2.0 
  cupertino_icons: ^1.0.8 
  image_picker: ^1.1.2 
  image: ^4.5.4 
  flutter_image_compress: ^2.0.0 
  cached_network_image: ^3.2.3
  camera: ^0.11.1 
  
  permission_handler: ^12.0.0+1
  path_drawing: ^1.0.0
  xml: ^6.2.0
  sqflite: ^2.2.0
  http: ^1.1.0
  universal_html: ^2.2.1 
  shared_preferences: ^2.5.3
  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.13.1
  showcaseview: ^4.0.1
  flutter_local_notifications: ^19.4.2
  pdf: ^3.11.3
  printing: ^5.14.2
  uuid: ^4.5.1
  cloudinary_api: ^1.1.1
  cloudinary_url_gen: ^1.8.0
  cloudinary_flutter: ^1.0.0
  cloudinary_public: ^0.23.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/bglogo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/aauplogo.png
    - lib/assets/logo1.png
    - lib/assets/backgrownd.png
    - assets/aauplogo.png
    - assets/Cairo-Regular.ttf
